#pragma once

#include "glm/glm.hpp"
#include "glm/gtc/matrix_transform.hpp"
#include "glm/gtc/type_ptr.hpp"

#include "Comet/Core/Application.h"
#include "Comet/Core/Assets.h"
#include "Comet/Core/Core.h"
#include "Comet/Core/KeyCodes.h"
#include "Comet/Core/Layer.h"
#include "Comet/Core/LayerStack.h"
#include "Comet/Core/Log.h"
#include "Comet/Core/MouseCodes.h"
#include "Comet/Core/OrthographicCameraController.h"
#include "Comet/Core/Time.h"
#include "Comet/Core/Window.h"

#include "Comet/Event/Event.h"
#include "Comet/Event/KeyEvent.h"
#include "Comet/Event/MouseEvent.h"
#include "Comet/Event/WindowEvent.h"

#include "Comet/Renderer/Buffer.h"
#include "Comet/Renderer/OrthographicCamera.h"
#include "Comet/Renderer/Renderer.h"
#include "Comet/Renderer/Renderer2D.h"
#include "Comet/Renderer/Shader.h"
#include "Comet/Renderer/Texture.h"
#include "Comet/Renderer/VertexArray.h"
